// <auto-generated />
using System;
using BhumiLogistics.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BhumiLogistics.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260921102955_AddLandUseAndSetbackToLandPlots")]
    partial class AddLandUseAndSetbackToLandPlots
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BhumiLogistics.Domain.Entities.HighwaySetbackStandard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("HighwayFrontageType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("SetbackDistanceInMeters")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.HasKey("Id");

                    b.HasIndex("HighwayFrontageType")
                        .IsUnique();

                    b.ToTable("HighwaySetbackStandards", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000001"),
                            HighwayFrontageType = "None",
                            SetbackDistanceInMeters = 0m
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000002"),
                            HighwayFrontageType = "StateHighwayFrontage",
                            Notes = "Approximate — verify against current Department of Roads standard.",
                            SetbackDistanceInMeters = 15m
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000003"),
                            HighwayFrontageType = "NationalHighwayFrontage",
                            Notes = "Approximate — verify against current Department of Roads standard.",
                            SetbackDistanceInMeters = 25m
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000004"),
                            HighwayFrontageType = "ExpresswayFrontage",
                            Notes = "Approximate — draft 2083 bill proposes 50m per side plus an additional 6m no-build buffer.",
                            SetbackDistanceInMeters = 50m
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000005"),
                            HighwayFrontageType = "CornerPlotDualFrontage",
                            Notes = "Conservative default for dual frontage — confirm which of the two roads governs.",
                            SetbackDistanceInMeters = 25m
                        });
                });

            modelBuilder.Entity("BhumiLogistics.Domain.Entities.LandPlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<decimal>("FrontageLengthInMeters")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<string>("HighwayFrontageType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsLeased")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<decimal>("LatitudeCoordinate")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<decimal>("LongitudeCoordinate")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("SetbackDistanceInMeters")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.HasKey("Id");

                    b.ToTable("LandPlots", (string)null);
                });

            modelBuilder.Entity("BhumiLogistics.Domain.Entities.LeaseOffer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<int>("DurationInYears")
                        .HasColumnType("integer");

                    b.Property<Guid>("LandPlotId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("LastModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<decimal>("OfferedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateOnly>("ProposedStartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("TenantName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("TenantUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LandPlotId");

                    b.ToTable("LeaseOffers", (string)null);
                });

            modelBuilder.Entity("BhumiLogistics.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("LastModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("BhumiLogistics.Domain.Entities.LandPlot", b =>
                {
                    b.OwnsOne("BhumiLogistics.Domain.ValueObjects.LandArea", "Area", b1 =>
                        {
                            b1.Property<Guid>("LandPlotId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("SizeInBigha")
                                .HasPrecision(10, 2)
                                .HasColumnType("numeric(10,2)")
                                .HasColumnName("SizeInBigha");

                            b1.Property<decimal>("SizeInKattha")
                                .HasPrecision(10, 2)
                                .HasColumnType("numeric(10,2)")
                                .HasColumnName("SizeInKattha");

                            b1.HasKey("LandPlotId");

                            b1.ToTable("LandPlots");

                            b1.WithOwner()
                                .HasForeignKey("LandPlotId");
                        });

                    b.OwnsOne("BhumiLogistics.Domain.ValueObjects.LandUseDeclaration", "LandUseDeclaration", b1 =>
                        {
                            b1.Property<Guid>("LandPlotId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Classification")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("LandUseClassification");

                            b1.Property<DateOnly?>("ConversionApprovalDate")
                                .HasColumnType("date")
                                .HasColumnName("LandUseConversionApprovalDate");

                            b1.Property<string>("ConversionApprovalReferenceNumber")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("LandUseConversionApprovalReferenceNumber");

                            b1.Property<string>("ConversionApprovingAuthority")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("LandUseConversionApprovingAuthority");

                            b1.HasKey("LandPlotId");

                            b1.ToTable("LandPlots");

                            b1.WithOwner()
                                .HasForeignKey("LandPlotId");
                        });

                    b.OwnsOne("BhumiLogistics.Domain.ValueObjects.OwnershipVerification", "OwnershipVerification", b1 =>
                        {
                            b1.Property<Guid>("LandPlotId")
                                .HasColumnType("uuid");

                            b1.Property<string>("KittaNumber")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("KittaNumber");

                            b1.Property<string>("LalpurjaReferenceNumber")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("LalpurjaReferenceNumber");

                            b1.Property<string>("LandIdentityNumber")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("LandIdentityNumber");

                            b1.Property<bool>("MohiTenancyDeclared")
                                .HasColumnType("boolean")
                                .HasColumnName("MohiTenancyDeclared");

                            b1.Property<string>("MohiTenancyNotes")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("MohiTenancyNotes");

                            b1.Property<string>("PowerOfAttorneyReferenceNumber")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("PowerOfAttorneyReferenceNumber");

                            b1.Property<string>("RegisteredOwnerName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("RegisteredOwnerName");

                            b1.Property<string>("RelationshipToOwner")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("RelationshipToOwner");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("OwnershipStatus");

                            b1.Property<string>("TenureType")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("TenureType");

                            b1.Property<string>("VerificationNotes")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("OwnershipVerificationNotes");

                            b1.Property<DateTimeOffset?>("VerifiedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("OwnershipVerifiedAtUtc");

                            b1.Property<Guid?>("VerifiedByUserId")
                                .HasColumnType("uuid")
                                .HasColumnName("OwnershipVerifiedByUserId");

                            b1.Property<string>("WardMunicipality")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("WardMunicipality");

                            b1.HasKey("LandPlotId");

                            b1.ToTable("LandPlots");

                            b1.WithOwner()
                                .HasForeignKey("LandPlotId");
                        });

                    b.OwnsOne("BhumiLogistics.Domain.ValueObjects.PlusCode", "PlusCode", b1 =>
                        {
                            b1.Property<Guid>("LandPlotId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("PlusCode");

                            b1.HasKey("LandPlotId");

                            b1.ToTable("LandPlots");

                            b1.WithOwner()
                                .HasForeignKey("LandPlotId");
                        });

                    b.Navigation("Area")
                        .IsRequired();

                    b.Navigation("LandUseDeclaration")
                        .IsRequired();

                    b.Navigation("OwnershipVerification")
                        .IsRequired();

                    b.Navigation("PlusCode")
                        .IsRequired();
                });

            modelBuilder.Entity("BhumiLogistics.Domain.Entities.LeaseOffer", b =>
                {
                    b.HasOne("BhumiLogistics.Domain.Entities.LandPlot", null)
                        .WithMany("LeaseOffers")
                        .HasForeignKey("LandPlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BhumiLogistics.Domain.Entities.LandPlot", b =>
                {
                    b.Navigation("LeaseOffers");
                });
#pragma warning restore 612, 618
        }
    }
}
